/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SobreNosRouteImport } from './routes/sobre-nos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as NiveisNivelRouteImport } from './routes/niveis.$nivel'
import { Route as AuthenticatedSimuladosIndexRouteImport } from './routes/_authenticated/simulados.index'
import { Route as AuthenticatedSimuladosNivelRouteImport } from './routes/_authenticated/simulados.$nivel'
import { Route as AuthenticatedAulasNivelModuloRouteImport } from './routes/_authenticated/aulas.$nivel.$modulo'
import { Route as AuthenticatedAulasNivelModuloLicaoRouteImport } from './routes/_authenticated/aulas.$nivel.$modulo.$licao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosRoute = SobreNosRouteImport.update({
  id: '/sobre-nos',
  path: '/sobre-nos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const NiveisNivelRoute = NiveisNivelRouteImport.update({
  id: '/niveis/$nivel',
  path: '/niveis/$nivel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSimuladosIndexRoute =
  AuthenticatedSimuladosIndexRouteImport.update({
    id: '/simulados/',
    path: '/simulados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSimuladosNivelRoute =
  AuthenticatedSimuladosNivelRouteImport.update({
    id: '/simulados/$nivel',
    path: '/simulados/$nivel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAulasNivelModuloRoute =
  AuthenticatedAulasNivelModuloRouteImport.update({
    id: '/aulas/$nivel/$modulo',
    path: '/aulas/$nivel/$modulo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAulasNivelModuloLicaoRoute =
  AuthenticatedAulasNivelModuloLicaoRouteImport.update({
    id: '/$licao',
    path: '/$licao',
    getParentRoute: () => AuthenticatedAulasNivelModuloRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/sobre-nos': typeof SobreNosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/niveis/$nivel': typeof NiveisNivelRoute
  '/simulados/$nivel': typeof AuthenticatedSimuladosNivelRoute
  '/simulados/': typeof AuthenticatedSimuladosIndexRoute
  '/aulas/$nivel/$modulo': typeof AuthenticatedAulasNivelModuloRouteWithChildren
  '/aulas/$nivel/$modulo/$licao': typeof AuthenticatedAulasNivelModuloLicaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/sobre-nos': typeof SobreNosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/niveis/$nivel': typeof NiveisNivelRoute
  '/simulados/$nivel': typeof AuthenticatedSimuladosNivelRoute
  '/simulados': typeof AuthenticatedSimuladosIndexRoute
  '/aulas/$nivel/$modulo': typeof AuthenticatedAulasNivelModuloRouteWithChildren
  '/aulas/$nivel/$modulo/$licao': typeof AuthenticatedAulasNivelModuloLicaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/sobre-nos': typeof SobreNosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/niveis/$nivel': typeof NiveisNivelRoute
  '/_authenticated/simulados/$nivel': typeof AuthenticatedSimuladosNivelRoute
  '/_authenticated/simulados/': typeof AuthenticatedSimuladosIndexRoute
  '/_authenticated/aulas/$nivel/$modulo': typeof AuthenticatedAulasNivelModuloRouteWithChildren
  '/_authenticated/aulas/$nivel/$modulo/$licao': typeof AuthenticatedAulasNivelModuloLicaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blog'
    | '/contato'
    | '/recuperar-senha'
    | '/reset-password'
    | '/sobre'
    | '/sobre-nos'
    | '/dashboard'
    | '/perfil'
    | '/niveis/$nivel'
    | '/simulados/$nivel'
    | '/simulados/'
    | '/aulas/$nivel/$modulo'
    | '/aulas/$nivel/$modulo/$licao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/contato'
    | '/recuperar-senha'
    | '/reset-password'
    | '/sobre'
    | '/sobre-nos'
    | '/dashboard'
    | '/perfil'
    | '/niveis/$nivel'
    | '/simulados/$nivel'
    | '/simulados'
    | '/aulas/$nivel/$modulo'
    | '/aulas/$nivel/$modulo/$licao'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/blog'
    | '/contato'
    | '/recuperar-senha'
    | '/reset-password'
    | '/sobre'
    | '/sobre-nos'
    | '/_authenticated/dashboard'
    | '/_authenticated/perfil'
    | '/niveis/$nivel'
    | '/_authenticated/simulados/$nivel'
    | '/_authenticated/simulados/'
    | '/_authenticated/aulas/$nivel/$modulo'
    | '/_authenticated/aulas/$nivel/$modulo/$licao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  ContatoRoute: typeof ContatoRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SobreRoute: typeof SobreRoute
  SobreNosRoute: typeof SobreNosRoute
  NiveisNivelRoute: typeof NiveisNivelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nos': {
      id: '/sobre-nos'
      path: '/sobre-nos'
      fullPath: '/sobre-nos'
      preLoaderRoute: typeof SobreNosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/niveis/$nivel': {
      id: '/niveis/$nivel'
      path: '/niveis/$nivel'
      fullPath: '/niveis/$nivel'
      preLoaderRoute: typeof NiveisNivelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/simulados/': {
      id: '/_authenticated/simulados/'
      path: '/simulados'
      fullPath: '/simulados/'
      preLoaderRoute: typeof AuthenticatedSimuladosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulados/$nivel': {
      id: '/_authenticated/simulados/$nivel'
      path: '/simulados/$nivel'
      fullPath: '/simulados/$nivel'
      preLoaderRoute: typeof AuthenticatedSimuladosNivelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aulas/$nivel/$modulo': {
      id: '/_authenticated/aulas/$nivel/$modulo'
      path: '/aulas/$nivel/$modulo'
      fullPath: '/aulas/$nivel/$modulo'
      preLoaderRoute: typeof AuthenticatedAulasNivelModuloRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aulas/$nivel/$modulo/$licao': {
      id: '/_authenticated/aulas/$nivel/$modulo/$licao'
      path: '/$licao'
      fullPath: '/aulas/$nivel/$modulo/$licao'
      preLoaderRoute: typeof AuthenticatedAulasNivelModuloLicaoRouteImport
      parentRoute: typeof AuthenticatedAulasNivelModuloRoute
    }
  }
}

interface AuthenticatedAulasNivelModuloRouteChildren {
  AuthenticatedAulasNivelModuloLicaoRoute: typeof AuthenticatedAulasNivelModuloLicaoRoute
}

const AuthenticatedAulasNivelModuloRouteChildren: AuthenticatedAulasNivelModuloRouteChildren =
  {
    AuthenticatedAulasNivelModuloLicaoRoute:
      AuthenticatedAulasNivelModuloLicaoRoute,
  }

const AuthenticatedAulasNivelModuloRouteWithChildren =
  AuthenticatedAulasNivelModuloRoute._addFileChildren(
    AuthenticatedAulasNivelModuloRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedSimuladosNivelRoute: typeof AuthenticatedSimuladosNivelRoute
  AuthenticatedSimuladosIndexRoute: typeof AuthenticatedSimuladosIndexRoute
  AuthenticatedAulasNivelModuloRoute: typeof AuthenticatedAulasNivelModuloRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedSimuladosNivelRoute: AuthenticatedSimuladosNivelRoute,
  AuthenticatedSimuladosIndexRoute: AuthenticatedSimuladosIndexRoute,
  AuthenticatedAulasNivelModuloRoute:
    AuthenticatedAulasNivelModuloRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  ContatoRoute: ContatoRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SobreRoute: SobreRoute,
  SobreNosRoute: SobreNosRoute,
  NiveisNivelRoute: NiveisNivelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
